<?php

/* Carrega Arquivos JS do tema */
/* ----------------------------------------- */
function bfriend_loadJS(){
  if (!is_admin()){
		// desregistrando o jquery nativo e registrando o do CDN do Google.
		wp_deregister_script('jquery');
		wp_register_script('jquery', '//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js', false, '3.2.1');
		wp_enqueue_script('jquery');

		$js = get_template_directory_uri() . '/assets/js/';
		wp_enqueue_script('propper',				'//cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js', ['jquery']);
		wp_enqueue_script('bootstrap-min',	'//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js', ['jquery','propper']);
		wp_enqueue_script('fancybox',				'//cdn.rawgit.com/fancyapps/fancybox/master/dist/jquery.fancybox.min.js', ['jquery']);
		wp_enqueue_script('slick',					'//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick.min.js', ['jquery']);

		wp_enqueue_script('offcanvas',		$js . 'bootstrap.offcanvas.min.js', ['jquery']);
		wp_enqueue_script('acf-maps', 		$js . 'maps.js', ['jquery']);
		wp_enqueue_script('mask', 				$js . 'jquery.mask.min.js', ['jquery']);
		wp_enqueue_script('codigo', 			$js . 'codigo.js', ['jquery']);
  }
}
add_action( 'wp_print_scripts', 'bfriend_loadJS' );


/* Carrega Arquivos CSS do tema */
/* ----------------------------------------- */
function bfriend_loadCSS(){
	$css = get_template_directory_uri() . '/assets/css/';
	wp_enqueue_style( 'offcanvas', 			$css . '_bootstrap.offcanvas.css' );
	wp_enqueue_style( 'fontawesome', 		'//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css', false, '4.6.3' );
	wp_enqueue_style( 'fancybox', 			'//cdn.rawgit.com/fancyapps/fancybox/60c37246/dist/jquery.fancybox.min.css' );
	wp_enqueue_style( 'slick', 					'//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick.min.css' );
	wp_enqueue_style( 'slick-theme', 		'//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick-theme.min.css' );
	wp_enqueue_style( 'slick-loader', 	'//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/ajax-loader.gif' );
}
add_action('wp_enqueue_scripts', 'bfriend_loadCSS');


// Avisa ao Wordpress para executar a função bfriend_setup()
// quando o 'after_setup_theme' hook roda.
add_action( 'after_setup_theme', 'bfriend_setup' );

if ( ! function_exists( 'bfriend_setup' ) ):
	// Configura os padrões do tema e suporte a algumas funções do wp.
	function bfriend_setup() {
		// Ativa o editor-style.css
		add_editor_style('assets/css/editor-style.css');

		// Ativa a imagem destacada
		add_theme_support( 'post-thumbnails' );

		// Registers theme menu's 
		register_nav_menus( array(
			'global' => __( 'Navegação Global', 'partner-programmer' ),
			'local' => __( 'Navegação Local', 'partner-programmer' ),
		) );
	}
endif;


/**
 * Makes some changes to the <title> tag, by filtering the output of wp_title().
 *
 * If we have a site description and we're viewing the home page or a blog posts
 * page (when using a static front page), then we will add the site description.
 *
 * If we're viewing a search result, then we're going to recreate the title entirely.
 * We're going to add page numbers to all titles as well, to the middle of a search
 * result title and the end of all other titles.
 *
 * The site title also gets added to all titles.
 *
 * @since Twenty Ten 1.0
 *
 * @param string $title Title generated by wp_title()
 * @param string $separator The separator passed to wp_title(). Twenty Ten uses a
 * 	vertical bar, "|", as a separator in header.php.
 * @return string The new title, ready for the <title> tag.
 */
function twentyten_filter_wp_title( $title, $separator ) {
	// Don't affect wp_title() calls in feeds.
	if ( is_feed() )
		return $title;

	// The $paged global variable contains the page number of a listing of posts.
	// The $page global variable contains the page number of a single post that is paged.
	// We'll display whichever one applies, if we're not looking at the first page.
	global $paged, $page;

	if ( is_search() ) {
		// If we're a search, let's start over:
		$title = sprintf( __( 'Search results for %s', 'twentyten' ), '"' . get_search_query() . '"' );
		// Add a page number if we're on page 2 or more:
		if ( $paged >= 2 )
			$title .= " $separator " . sprintf( __( 'Page %s', 'twentyten' ), $paged );
		// Add the site name to the end:
		$title .= " $separator " . get_bloginfo( 'name', 'display' );
		// We're done. Let's send the new title back to wp_title():
		return $title;
	}

	// Otherwise, let's start by adding the site name to the end:
	$title .= get_bloginfo( 'name', 'display' );

	// If we have a site description and we're on the home/front page, add the description:
	$site_description = get_bloginfo( 'description', 'display' );
	if ( $site_description && ( is_home() || is_front_page() ) )
		$title .= " $separator " . $site_description;

	// Add a page number if necessary:
	if ( $paged >= 2 || $page >= 2 )
		$title .= " $separator " . sprintf( __( 'Page %s', 'twentyten' ), max( $paged, $page ) );

	// Return the new title to wp_title():
	return $title;
}
add_filter( 'wp_title', 'twentyten_filter_wp_title', 10, 2 );


/**
 * Register widgetized areas, including two sidebars and four widget-ready columns in the footer.
 *
 * To override twentyten_widgets_init() in a child theme, remove the action hook and add your own
 * function tied to the init hook.
 *
 * @since Twenty Ten 1.0
 * @uses register_sidebar
 */
function twentyten_widgets_init() {
	// Area 1, located at the top of the sidebar.
	register_sidebar( array(
		'name' => __( 'Sidebar', 'twentyten' ),
		'id' => 'sidebar-principal',
		'description' => __( 'Arraste os itens desejados até aqui. ', 'twentyten' ),
		'before_widget' => '<div class="widget %2$s" id="%1$s">',
		'after_widget' => '</div>',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );

	// Sidebar for products
	register_sidebar( array(
		'name' => __( 'Sidebar produtos', 'twentyten' ),
		'id' => 'sidebar-produtos',
		'description' => __( 'Arraste os itens desejados até aqui. ', 'twentyten' ),
		'before_widget' => '<div class="widget %2$s" id="%1$s">',
		'after_widget' => '</div>',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
}

/** Register sidebars by running twentyten_widgets_init() on the widgets_init hook. */
add_action( 'widgets_init', 'twentyten_widgets_init' );


/* Adiciona editor se usuário for editor no body-class */
/* --------------------------------------------------- */
function role_user_body_class( $classes ) {
	if( current_user_can('editor') ) { $classes .= ' editor'; }
  return trim( $classes );
}
add_filter( 'admin_body_class', 'role_user_body_class' );

/* Cria páginas ao instalar o tema */
/* ----------------------------------------- */
// programmatically create some basic pages, and then set Home and Blog
// setup a function to check if these pages exist
function the_slug_exists($post_name) {
	global $wpdb;
	if($wpdb->get_row("SELECT post_name FROM wp_posts WHERE post_name = '" . $post_name . "'", 'ARRAY_A')) {
		return true;
	} else {
		return false;
	}
}

$paginas = [
	// [Title, Content, 'Slug']
	['Home', '', 'home'],
	['Blog', '', 'blog'],
	['Institucional', '', 'institucional'],
	['Contato', '', 'contato'],
];
// Cria as páginas
if (isset($_GET['activated']) && is_admin()){
	foreach ($paginas as $pagina) {
		$page_check = get_page_by_title($pagina[0]);
		if(!isset($page_check->ID) && !the_slug_exists($pagina[2])){
		    $newPageId = wp_insert_post(array(
		    	'post_type' => 'page',
		    	'post_title' => $pagina[0],
		    	'post_content' => $pagina[1],
		    	'post_status' => 'publish',
		    	'post_author' => 1,
		    	'post_slug' => $pagina[2]
		    ));
		    if ($pagina[0] == 'Home') { update_option( 'page_on_front', $newPageId ); update_option( 'show_on_front', 'page' ); }
		    if ($pagina[0] == 'Blog') { update_option( 'page_for_posts', $newPageId ); }
		}
	}
}
/* ----------------------------------------- Cria páginas ao instalar o tema */

/*
	Filtro para criar container responsivo nos embeds do the_content
	Style no @angolanos-default-styles.less
/* ----------------------------------------- */
	add_filter('embed_oembed_html', 'wrap_embed_with_div', 10, 3);
	function wrap_embed_with_div($html, $url, $attr) {
    return "<div class=\"responsive-container\">".$html."</div>";
	}
/* ----------------------------------------- Filtro para criar container responsivo nos embeds do the_content */